# Generated by Django 5.2.9 on 2025-12-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da loteria (ex: Mega-Sena)', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador URL-friendly (ex: megasena)', unique=True, verbose_name='Slug')),
                ('api_identifier', models.CharField(help_text='Identificador usado na API da CAIXA (ex: megasena)', max_length=50, verbose_name='Identificador API')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('numbers_count', models.PositiveSmallIntegerField(help_text='Quantos números são sorteados (ex: 6 para Mega-Sena)', verbose_name='Quantidade de números')),
                ('min_number', models.PositiveSmallIntegerField(default=1, verbose_name='Número mínimo')),
                ('max_number', models.PositiveSmallIntegerField(help_text='Maior número possível (ex: 60 para Mega-Sena)', verbose_name='Número máximo')),
                ('color', models.CharField(default='#209869', help_text='Cor hexadecimal para UI (ex: #209869)', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loteria',
                'verbose_name_plural': 'Loterias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número do concurso')),
                ('draw_date', models.DateField(verbose_name='Data do sorteio')),
                ('numbers', models.JSONField(help_text='Lista de números em ordem crescente', verbose_name='Números sorteados')),
                ('numbers_draw_order', models.JSONField(blank=True, help_text='Lista de números na ordem em que foram sorteados', null=True, verbose_name='Números na ordem do sorteio')),
                ('is_accumulated', models.BooleanField(default=False, verbose_name='Acumulado')),
                ('accumulated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor acumulado')),
                ('next_draw_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimativa próximo concurso')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Arrecadação total')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local do sorteio')),
                ('city_state', models.CharField(blank=True, max_length=100, verbose_name='Cidade/UF')),
                ('next_draw_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo concurso')),
                ('next_draw_date', models.DateField(blank=True, null=True, verbose_name='Data próximo concurso')),
                ('raw_data', models.JSONField(default=dict, help_text='Resposta completa da API da CAIXA', verbose_name='Dados brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='lotteries.lottery', verbose_name='Loteria')),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='PrizeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(help_text='Número da faixa (1 = maior prêmio)', verbose_name='Faixa')),
                ('description', models.CharField(help_text='Descrição da faixa (ex: 6 acertos)', max_length=100, verbose_name='Descrição')),
                ('matches', models.PositiveSmallIntegerField(blank=True, help_text='Número de acertos para esta faixa', null=True, verbose_name='Acertos')),
                ('winners_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de ganhadores')),
                ('prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do prêmio')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_tiers', to='lotteries.draw', verbose_name='Sorteio')),
            ],
            options={
                'verbose_name': 'Faixa de Premiação',
                'verbose_name_plural': 'Faixas de Premiação',
                'ordering': ['draw', 'tier'],
            },
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['lottery', '-number'], name='lotteries_d_lottery_3977ef_idx'),
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['draw_date'], name='lotteries_d_draw_da_9952e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('lottery', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='prizetier',
            unique_together={('draw', 'tier')},
        ),
    ]
