# Generated by Django 5.2.9 on 2025-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='max_number',
            field=models.PositiveIntegerField(help_text='Maior número possível (ex: 60 para Mega-Sena)', verbose_name='Número máximo'),
        ),
    ]
