# Generated by Django 5.2.9 on 2025-12-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotteries', '0002_alter_lottery_max_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('config', models.JSONField(default=dict, help_text="JSON com regras de geração (ex: {'min_sum': 100, 'exclude': [1, 2]})", verbose_name='Configuração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='lotteries.lottery', verbose_name='Loteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_presets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preset de Geração',
                'verbose_name_plural': 'Presets de Geração',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Quantidade de jogos solicitados', verbose_name='Quantidade')),
                ('result', models.JSONField(default=list, help_text='Lista de jogos gerados com seus metadados', verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_runs', to='lotteries.lottery', verbose_name='Loteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_runs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='generator.preset', verbose_name='Preset utilizado')),
            ],
            options={
                'verbose_name': 'Execução do Gerador',
                'verbose_name_plural': 'Execuções do Gerador',
                'ordering': ['-created_at'],
            },
        ),
    ]
