# Generated by Django 5.2.9 on 2025-12-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotteries', '0002_alter_lottery_max_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_value', models.IntegerField(help_text='Soma de todas as dezenas', verbose_name='Soma')),
                ('even_count', models.PositiveSmallIntegerField(help_text='Quantidade de números pares', verbose_name='Pares')),
                ('odd_count', models.PositiveSmallIntegerField(help_text='Quantidade de números ímpares', verbose_name='Ímpares')),
                ('range_value', models.IntegerField(help_text='Diferença entre o maior e o menor número', verbose_name='Amplitude')),
                ('prime_count', models.PositiveSmallIntegerField(help_text='Quantidade de números primos', verbose_name='Primos')),
                ('consecutive_count', models.PositiveSmallIntegerField(help_text='Quantidade de pares consecutivos (ex: 1,2 = 1 par)', verbose_name='Consecutivos')),
                ('repeated_from_previous', models.PositiveSmallIntegerField(default=0, help_text='Quantidade de números repetidos do concurso anterior', verbose_name='Repetidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='lotteries.draw', verbose_name='Sorteio')),
            ],
            options={
                'verbose_name': 'Estatística do Sorteio',
                'verbose_name_plural': 'Estatísticas dos Sorteios',
                'ordering': ['-draw__number'],
            },
        ),
    ]
