# Generated by Django 5.2.9 on 2025-12-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotteries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(help_text='Lista de números apostados (ex: [1, 5, 23, 34, 45, 60])', verbose_name='Números')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem da linha no bilhete', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Linha de Aposta',
                'verbose_name_plural': 'Linhas de Aposta',
                'ordering': ['ticket', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TicketCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da conferência')),
                ('total_prize', models.DecimalField(decimal_places=2, default=0, help_text='Soma de todos os prêmios das linhas', max_digits=15, verbose_name='Prêmio total')),
                ('best_tier', models.PositiveSmallIntegerField(blank=True, help_text='Melhor faixa de premiação atingida (1 = maior prêmio)', null=True, verbose_name='Melhor faixa')),
                ('best_hits', models.PositiveSmallIntegerField(default=0, help_text='Maior quantidade de acertos em uma linha', verbose_name='Maior acertos')),
                ('winning_lines_count', models.PositiveIntegerField(default=0, help_text='Quantidade de linhas que ganharam algum prêmio', verbose_name='Linhas premiadas')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_checks', to='lotteries.draw', verbose_name='Sorteio')),
            ],
            options={
                'verbose_name': 'Resultado de Conferência',
                'verbose_name_plural': 'Resultados de Conferências',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='LineCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveSmallIntegerField(default=0, help_text='Quantidade de números acertados', verbose_name='Acertos')),
                ('hit_numbers', models.JSONField(default=list, help_text='Lista dos números que foram acertados', verbose_name='Números acertados')),
                ('prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do prêmio')),
                ('prize_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_wins', to='lotteries.prizetier', verbose_name='Faixa de prêmio')),
                ('check_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_results', to='tickets.ticketcheckresult', verbose_name='Resultado da conferência')),
                ('bet_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='tickets.userbetline', verbose_name='Linha de aposta')),
            ],
            options={
                'verbose_name': 'Resultado de Linha',
                'verbose_name_plural': 'Resultados de Linhas',
                'ordering': ['check_result', 'bet_line__order'],
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nome opcional para identificar o bilhete', max_length=100, verbose_name='Nome')),
                ('numbers_per_bet', models.PositiveSmallIntegerField(help_text='Quantidade de números em cada linha (ex: 6, 7, 8 para Mega-Sena)', verbose_name='Números por aposta')),
                ('is_active', models.BooleanField(default=True, help_text='Se o bilhete está ativo para conferências', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to='lotteries.lottery', verbose_name='Loteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userbetline',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_lines', to='tickets.userticket', verbose_name='Bilhete'),
        ),
        migrations.AddField(
            model_name='ticketcheckresult',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='tickets.userticket', verbose_name='Bilhete'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketcheckresult',
            unique_together={('ticket', 'draw')},
        ),
    ]
